# Generated by tool/bump.py from https://updates.lintcrux.app/manifest.json. Do not edit.
cask "lintcrux" do
  version "0.8.0"
  sha256 "f69ca60c80c77e6bf3d818af975e83bffb85722d3a158aba8a9e965240540066"

  url "https://updates.lintcrux.app/#{version}/LintCrux-#{version}.dmg"
  name "LintCrux"
  desc "RTL lint dashboard for Verilator, Verible, Slang, GHDL and Yosys"
  homepage "https://lintcrux.app/"

  livecheck do
    url "https://updates.lintcrux.app/manifest.json"
    strategy :json do |json|
      json.dig("latest", "version")
    end
  end

  depends_on macos: :monterey

  app "LintCrux Pro.app"

  zap trash: [
    "~/Library/Application Support/com.ferriteengineering.lintcruxPro",
    "~/Library/Caches/com.ferriteengineering.lintcruxPro",
    "~/Library/Containers/com.ferriteengineering.lintcruxPro",
    "~/Library/Preferences/com.ferriteengineering.lintcruxPro.plist",
    "~/Library/Saved Application State/com.ferriteengineering.lintcruxPro.savedState",
  ]
end
