# Generated by tool/bump.py from https://updates.lintcrux.app/manifest.json. Do not edit.
cask "lintcrux" do
  version "1.0.0"
  sha256 "425d576d6d7a44ce6a7a2f97f3c22b9baec0fdf8d384b8bea0c0795d5ae3aeeb"

  url "https://updates.lintcrux.app/#{version}/LintCrux-#{version}.dmg"
  name "LintCrux"
  desc "RTL lint dashboard for Verilator, Verible, Slang, GHDL and Yosys"
  homepage "https://lintcrux.app/"

  livecheck do
    url "https://updates.lintcrux.app/manifest.json"
    strategy :json do |json|
      json.dig("latest", "version")
    end
  end

  depends_on macos: :monterey

  app "LintCrux.app"

  zap trash: [
    "~/Library/Application Support/com.ferriteengineering.lintcruxPro",
    "~/Library/Caches/com.ferriteengineering.lintcruxPro",
    "~/Library/Containers/com.ferriteengineering.lintcruxPro",
    "~/Library/Preferences/com.ferriteengineering.lintcruxPro.plist",
    "~/Library/Saved Application State/com.ferriteengineering.lintcruxPro.savedState",
  ]
end
