# Generated by tool/bump.py from https://updates.netcrux.app/manifest.json. Do not edit.
cask "netcrux" do
  version "1.0.0"
  sha256 "b38f6600e47a701eb9836143a5414ee51eebac7bd2950ee08e605eb53067b9b5"

  url "https://updates.netcrux.app/#{version}/NetCrux-#{version}.dmg"
  name "NetCrux"
  desc "Hierarchical RTL schematic browser and signal tracer"
  homepage "https://netcrux.app/"

  livecheck do
    url "https://updates.netcrux.app/manifest.json"
    strategy :json do |json|
      json.dig("latest", "version")
    end
  end

  depends_on macos: :monterey

  app "NetCrux.app"

  zap trash: [
    "~/Library/Application Support/com.ferriteengineering.netcruxPro",
    "~/Library/Caches/com.ferriteengineering.netcruxPro",
    "~/Library/Containers/com.ferriteengineering.netcruxPro",
    "~/Library/Preferences/com.ferriteengineering.netcruxPro.plist",
    "~/Library/Saved Application State/com.ferriteengineering.netcruxPro.savedState",
  ]
end
