# Generated by tool/bump.py from https://updates.netcrux.app/manifest.json. Do not edit.
cask "netcrux" do
  version "0.8.0"
  sha256 "ef7dba0faf8bf2c89a63a6097b112b6c67f902b224c6dbe218b4164286dfda86"

  url "https://updates.netcrux.app/#{version}/NetCrux-#{version}.dmg"
  name "NetCrux"
  desc "Hierarchical RTL schematic browser and signal tracer"
  homepage "https://netcrux.app/"

  livecheck do
    url "https://updates.netcrux.app/manifest.json"
    strategy :json do |json|
      json.dig("latest", "version")
    end
  end

  depends_on macos: :monterey

  app "NetCrux Pro.app"

  zap trash: [
    "~/Library/Application Support/com.ferriteengineering.netcruxPro",
    "~/Library/Caches/com.ferriteengineering.netcruxPro",
    "~/Library/Containers/com.ferriteengineering.netcruxPro",
    "~/Library/Preferences/com.ferriteengineering.netcruxPro.plist",
    "~/Library/Saved Application State/com.ferriteengineering.netcruxPro.savedState",
  ]
end
