# Generated by tool/bump.py from https://updates.simcrux.app/manifest.json. Do not edit.
cask "simcrux" do
  version "1.0.0"
  sha256 "fa9cc14f65e7d8cefd6778a79f5ec270ed280818d541d48c6d524373310b0275"

  url "https://updates.simcrux.app/#{version}/SimCrux-#{version}.dmg"
  name "SimCrux"
  desc "Regression dashboard for Icarus, Verilator, GHDL and cocotb"
  homepage "https://simcrux.app/"

  livecheck do
    url "https://updates.simcrux.app/manifest.json"
    strategy :json do |json|
      json.dig("latest", "version")
    end
  end

  depends_on macos: :monterey

  app "SimCrux.app"

  zap trash: [
    "~/Library/Application Support/com.ferriteengineering.simcruxPro",
    "~/Library/Caches/com.ferriteengineering.simcruxPro",
    "~/Library/Containers/com.ferriteengineering.simcruxPro",
    "~/Library/Preferences/com.ferriteengineering.simcruxPro.plist",
    "~/Library/Saved Application State/com.ferriteengineering.simcruxPro.savedState",
  ]
end
