# Generated by tool/bump.py from https://updates.simcrux.app/manifest.json. Do not edit.
cask "simcrux" do
  version "0.8.0"
  sha256 "548ec95c8f2876605d64127f130fe19ff3b470ad9a2f9d3ad4ed92e3c0e6111e"

  url "https://updates.simcrux.app/#{version}/SimCrux-#{version}.dmg"
  name "SimCrux"
  desc "Regression dashboard for Icarus, Verilator, GHDL and cocotb"
  homepage "https://simcrux.app/"

  livecheck do
    url "https://updates.simcrux.app/manifest.json"
    strategy :json do |json|
      json.dig("latest", "version")
    end
  end

  depends_on macos: :monterey

  app "SimCrux Pro.app"

  zap trash: [
    "~/Library/Application Support/com.ferriteengineering.simcruxPro",
    "~/Library/Caches/com.ferriteengineering.simcruxPro",
    "~/Library/Containers/com.ferriteengineering.simcruxPro",
    "~/Library/Preferences/com.ferriteengineering.simcruxPro.plist",
    "~/Library/Saved Application State/com.ferriteengineering.simcruxPro.savedState",
  ]
end
