# Generated by tool/bump.py from https://updates.wavecrux.app/manifest.json. Do not edit.
cask "wavecrux" do
  version "0.8.0"
  sha256 "48f529946f80e5676b0cf07cb40337156183304e3c375b41b72603d8f646499d"

  url "https://updates.wavecrux.app/#{version}/WaveCrux-#{version}.dmg"
  name "WaveCrux"
  desc "Waveform viewer for VCD, FST, GHW and LXT simulation dumps"
  homepage "https://wavecrux.app/"

  livecheck do
    url "https://updates.wavecrux.app/manifest.json"
    strategy :json do |json|
      json.dig("latest", "version")
    end
  end

  depends_on macos: :monterey

  app "WaveCrux Pro.app"

  zap trash: [
    "~/Library/Application Support/com.ferriteengineering.wavecruxPro",
    "~/Library/Caches/com.ferriteengineering.wavecruxPro",
    "~/Library/Containers/com.ferriteengineering.wavecruxPro",
    "~/Library/Preferences/com.ferriteengineering.wavecruxPro.plist",
    "~/Library/Saved Application State/com.ferriteengineering.wavecruxPro.savedState",
  ]
end
