# Generated by tool/bump.py from https://updates.wavecrux.app/manifest.json. Do not edit.
cask "wavecrux" do
  version "1.0.0"
  sha256 "4b04d689310bb6eddead2fb10787d56540d79a8c1e915358ab69aed37d5f86e6"

  url "https://updates.wavecrux.app/#{version}/WaveCrux-#{version}.dmg"
  name "WaveCrux"
  desc "Waveform viewer for VCD, FST, GHW and LXT simulation dumps"
  homepage "https://wavecrux.app/"

  livecheck do
    url "https://updates.wavecrux.app/manifest.json"
    strategy :json do |json|
      json.dig("latest", "version")
    end
  end

  depends_on macos: :monterey

  app "WaveCrux.app"

  zap trash: [
    "~/Library/Application Support/com.ferriteengineering.wavecruxPro",
    "~/Library/Caches/com.ferriteengineering.wavecruxPro",
    "~/Library/Containers/com.ferriteengineering.wavecruxPro",
    "~/Library/Preferences/com.ferriteengineering.wavecruxPro.plist",
    "~/Library/Saved Application State/com.ferriteengineering.wavecruxPro.savedState",
  ]
end
