# Generated by tool/bump.py from https://updates.wavecrux.app/manifest.json. Do not edit.
cask "wavecrux" do
  version "1.0.1"
  sha256 "d00ce6db8209563b386c37045e7436207f70c67afa6aefe54fec63c8a44f036d"

  url "https://updates.wavecrux.app/#{version}/WaveCrux-#{version}.dmg"
  name "WaveCrux"
  desc "Waveform viewer for VCD, FST, GHW and LXT simulation dumps"
  homepage "https://wavecrux.app/"

  livecheck do
    url "https://updates.wavecrux.app/manifest.json"
    strategy :json do |json|
      json.dig("latest", "version")
    end
  end

  depends_on macos: :monterey

  app "WaveCrux.app"

  zap trash: [
    "~/Library/Application Support/com.ferriteengineering.wavecruxPro",
    "~/Library/Caches/com.ferriteengineering.wavecruxPro",
    "~/Library/Containers/com.ferriteengineering.wavecruxPro",
    "~/Library/Preferences/com.ferriteengineering.wavecruxPro.plist",
    "~/Library/Saved Application State/com.ferriteengineering.wavecruxPro.savedState",
  ]
end
