#!/usr/bin/env python3
"""Render every cask and formula in this tap from the live update manifests.

The tap never decides which version is current. Each product's update manifest,
https://updates.<product>.app/manifest.json, does: it is the file the installed
apps poll, and a release is live when that file says so. This script mirrors
it, so a release reaches Homebrew when its manifest goes live and never before.

Two independent sources must agree before anything is written: the manifest's
checksum for the DMG, and the SHA256SUMS file the release build published next
to it. A disagreement means a broken release, and the script stops rather than
publish it.

    python3 tool/bump.py                                   # rewrite Casks/ and Formula/
    python3 tool/bump.py --check                           # exit 1 if anything would change
    python3 tool/bump.py --github-output "$GITHUB_OUTPUT"  # CI: also report what changed

Everything under Casks/ and Formula/ is generated. Edit the templates here.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import time
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
USER_AGENT = "ferrite-engineering-homebrew-tap/1 (+https://github.com/Ferrite-Engineering/homebrew-tap)"
SEMVER = re.compile(r"^(\d+)\.(\d+)\.(\d+)$")

# The first release whose CLI the formula can honestly test. The 0.8.0 macOS
# binaries were signed without an entitlement the Dart runtime needs and are
# killed at launch (exit 137), and every 0.8.0 build answers `--version` with
# "lintcrux 0.1.0". Both are fixed at source. Before this version the tap
# carries no formula at all.
CLI_FIRST_VERSION = (1, 0, 0)

# The newest release whose app bundle carries the tier in its name
# ("WaveCrux Pro.app"). Every later release is named for the product alone,
# because one binary serves every tier and the name cannot follow a licence.
LAST_PRO_SUFFIXED_APP = (0, 8, 0)


@dataclass(frozen=True)
class Product:
    token: str
    name: str
    desc: str

    @property
    def host(self) -> str:
        return f"https://updates.{self.token}.app"

    @property
    def bundle_id(self) -> str:
        # Every download is the Pro overlay build, unlocked by licence, so the
        # Pro bundle id is the one a Homebrew install writes its data under.
        return f"com.ferriteengineering.{self.token}Pro"


PRODUCTS = (
    Product("wavecrux", "WaveCrux", "Waveform viewer for VCD, FST, GHW and LXT simulation dumps"),
    Product("netcrux", "NetCrux", "Hierarchical RTL schematic browser and signal tracer"),
    Product("lintcrux", "LintCrux", "RTL lint dashboard for Verilator, Verible, Slang, GHDL and Yosys"),
    Product("simcrux", "SimCrux", "Regression dashboard for Icarus, Verilator, GHDL and cocotb"),
)

CASK = """\
# Generated by tool/bump.py from {host}/manifest.json. Do not edit.
cask "{token}" do
  version "{version}"
  sha256 "{sha256}"

  url "{host}/#{{version}}/{name}-#{{version}}.dmg"
  name "{name}"
  desc "{desc}"
  homepage "https://{token}.app/"

  livecheck do
    url "{host}/manifest.json"
    strategy :json do |json|
      json.dig("latest", "version")
    end
  end

  depends_on macos: :monterey

  app "{app}"

  zap trash: [
    "~/Library/Application Support/{bundle_id}",
    "~/Library/Caches/{bundle_id}",
    "~/Library/Containers/{bundle_id}",
    "~/Library/Preferences/{bundle_id}.plist",
    "~/Library/Saved Application State/{bundle_id}.savedState",
  ]
end
"""

# One archive per platform, so each URL lives in its arch block, and Homebrew
# finds no URL at all on Intel macOS or ARM Linux, where no archive exists.
# `version` must be explicit: Homebrew reads "64" out of "linux-x64".
FORMULA = """\
# Generated by tool/bump.py from {host}/manifest.json. Do not edit.
class LintcruxCli < Formula
  desc "Headless RTL lint runner for CI pipelines"
  homepage "https://lintcrux.app/"
  version "{version}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "{host}/{version}/lintcrux-cli-{version}-macos-arm64.zip"
      sha256 "{macos_sha256}"
    end
  end

  on_linux do
    on_intel do
      url "{host}/{version}/lintcrux-cli-{version}-linux-x64.tar.gz"
      sha256 "{linux_sha256}"
    end
  end

  def install
    bin.install "lintcrux"
  end

  test do
    assert_equal "lintcrux #{{version}}", shell_output("#{{bin}}/lintcrux --version").strip
  end
end
"""


class ReleaseError(Exception):
    """The live release is inconsistent. Publishing it would be wrong."""


def fetch(url: str) -> str:
    request = urllib.request.Request(
        url,
        # The manifest route is edge-cached for 60 s and its cache key ignores
        # the query string, so only this header reaches the live file.
        headers={"User-Agent": USER_AGENT, "Cache-Control": "no-cache"},
    )
    for attempt in range(3):
        try:
            with urllib.request.urlopen(request, timeout=30) as response:
                return response.read().decode("utf-8")
        except (urllib.error.URLError, TimeoutError) as error:
            if attempt == 2:
                raise ReleaseError(f"{url}: {error}") from error
            time.sleep(5 * (attempt + 1))
    raise AssertionError("unreachable")


def parse_version(text: str, where: str) -> tuple[int, int, int]:
    match = SEMVER.match(text)
    if not match:
        raise ReleaseError(f"{where}: version {text!r} is not MAJOR.MINOR.PATCH")
    return tuple(int(part) for part in match.groups())  # type: ignore[return-value]


def parse_sums(text: str) -> dict[str, str]:
    sums = {}
    for line in text.splitlines():
        # Releases up to 0.8.0 wrote CRLF on the Windows rows; a trailing \r
        # would otherwise end up in the file name.
        line = line.strip()
        if not line:
            continue
        digest, _, name = line.partition(" ")
        sums[name.strip().lstrip("*")] = digest.lower()
    return sums


def render(product: Product) -> tuple[str, dict[str, str]]:
    """Returns (version, {relative path: file contents}) for one product."""
    manifest = json.loads(fetch(f"{product.host}/manifest.json"))
    latest = manifest["latest"]
    version = latest["version"]
    suffixed = parse_version(version, f"{product.token} manifest") <= LAST_PRO_SUFFIXED_APP

    dmg = f"{product.name}-{version}.dmg"
    dmg_url = f"{product.host}/{version}/{dmg}"
    advertised = latest["downloads"].get("macos_universal")
    if advertised != dmg_url:
        raise ReleaseError(
            f"{product.token}: manifest advertises {advertised!r} for macOS, the cask expects {dmg_url!r}"
        )

    sums = parse_sums(fetch(f"{product.host}/{version}/SHA256SUMS"))
    if dmg not in sums:
        raise ReleaseError(f"{product.token}: {dmg} is not in {version}/SHA256SUMS")
    manifest_sha = latest["checksums"].get("macos_universal", "").removeprefix("sha256:").lower()
    if manifest_sha != sums[dmg]:
        raise ReleaseError(
            f"{product.token}: the manifest says {dmg} is {manifest_sha or '(missing)'}, SHA256SUMS says {sums[dmg]}"
        )

    fields = dict(
        host=product.host,
        token=product.token,
        name=product.name,
        app=f"{product.name} Pro.app" if suffixed else f"{product.name}.app",
        desc=product.desc,
        version=version,
        sha256=sums[dmg],
        bundle_id=product.bundle_id,
    )
    files = {f"Casks/{product.token}.rb": CASK.format(**fields)}
    if product.token == "lintcrux" and parse_version(version, "lintcrux-cli") >= CLI_FIRST_VERSION:
        files["Formula/lintcrux-cli.rb"] = render_cli_formula(product, version, sums)
    return version, files


def render_cli_formula(product: Product, version: str, sums: dict[str, str]) -> str:
    def digest(name: str) -> str:
        if name not in sums:
            raise ReleaseError(f"{product.token}: {name} is not in {version}/SHA256SUMS")
        return sums[name]

    return FORMULA.format(
        host=product.host,
        version=version,
        macos_sha256=digest(f"lintcrux-cli-{version}-macos-arm64.zip"),
        linux_sha256=digest(f"lintcrux-cli-{version}-linux-x64.tar.gz"),
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="write nothing; exit 1 if anything would change")
    parser.add_argument("--github-output", type=Path, help="append what changed here, for the workflow")
    args = parser.parse_args()

    rendered: dict[str, str] = {}
    versions: dict[str, str] = {}
    try:
        for product in PRODUCTS:
            versions[product.token], files = render(product)
            rendered.update(files)
    except ReleaseError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    # Casks/ and Formula/ hold nothing but generated files, so a file this run
    # did not render is stale and goes.
    existing = {
        path.relative_to(ROOT).as_posix()
        for directory in ("Casks", "Formula")
        for path in (ROOT / directory).glob("*.rb")
    }
    changed = []
    for relative in sorted(existing | rendered.keys()):
        path = ROOT / relative
        text = rendered.get(relative)
        if text is not None and path.exists() and path.read_text(encoding="utf-8") == text:
            continue
        changed.append(relative)
        if args.check:
            continue
        if text is None:
            path.unlink()
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")

    for relative in changed:
        verb = "remove" if relative not in rendered else "update"
        print(f"{'would ' + verb if args.check else verb + 'd'} {relative}")
    if not changed:
        print("up to date: " + ", ".join(f"{token} {version}" for token, version in versions.items()))

    if args.github_output:
        def flag(value: bool) -> str:
            return "true" if value else "false"

        with args.github_output.open("a", encoding="utf-8") as out:
            out.write(f"casks_changed={flag(any(r.startswith('Casks/') for r in changed))}\n")
            out.write(f"cli_changed={flag(any(r.startswith('Formula/') for r in changed))}\n")
            out.write(f"cli={flag('Formula/lintcrux-cli.rb' in rendered)}\n")

    return 1 if args.check and changed else 0


if __name__ == "__main__":
    sys.exit(main())
