# Generated by tool/bump.py from https://updates.lintcrux.app/manifest.json. Do not edit.
class LintcruxCli < Formula
  desc "Headless RTL lint runner for CI pipelines"
  homepage "https://lintcrux.app/"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://updates.lintcrux.app/1.0.0/lintcrux-cli-1.0.0-macos-arm64.zip"
      sha256 "c7fe63696a3627dbf32360169c9a3be657ab0ae303a7f8636b57e9c06bf45c07"
    end
  end

  on_linux do
    on_intel do
      url "https://updates.lintcrux.app/1.0.0/lintcrux-cli-1.0.0-linux-x64.tar.gz"
      sha256 "5cc81faa53c3608e665c5e1ebf4df3baafc8a90231ab12cb91d58b6ebf6702ca"
    end
  end

  def install
    bin.install "lintcrux"
  end

  test do
    assert_equal "lintcrux #{version}", shell_output("#{bin}/lintcrux --version").strip
  end
end
