# Generated by tool/bump.py from https://updates.lintcrux.app/manifest.json. Do not edit.
class LintcruxCli < Formula
  desc "Headless RTL lint runner for CI pipelines"
  homepage "https://lintcrux.app/"
  url "https://updates.lintcrux.app/0.8.0/lintcrux-cli-0.8.0-linux-x64.tar.gz"
  sha256 "1ed9be42f51c9dd34a1afd622eb81a12f6feda2d659febb529efc65e03d43a48"
  license "Apache-2.0"

  depends_on arch: :x86_64
  depends_on :linux

  def install
    bin.install "lintcrux"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lintcrux --version")
  end
end
